openapi: 3.0.0
servers:
  - description: localhost
    url: http://localhost:9001/
info:
  title: 组件视图
  description: 组件中的视图相关api接口
  version: v1
parameters:
  Ones-Auth-Token:
    name: Ones-Auth-Token
    in: header
    description: Ones auth token
    required: true
    schema:
      type: string
  Ones-User-ID:
    name: Ones-User-ID
    in: header
    description: Ones user id
    required: true
    schema:
      type: string
  comUUID:
    name: comUUID
    in: path
    description: 组件 uuid
    required: true
    minLength: 8
    maxLength: 8
    schema:
      type: string
  projectUUID:
    name: projectUUID
    in: path
    description: 项目UUID
    required: true
    minLength: 16
    maxLength: 16
    schema:
      type: string
  teamUUID:
    name: teamUUID
    in: path
    description: 团队UUID
    required: true
    minLength: 8
    maxLength: 8
    schema:
      type: string
  viewUUID:
    name: viewUUID
    in: path
    description: 视图UUID
    required: true
    minLength: 8
    maxLength: 8
    schema:
      type: string
paths:
  /team/{teamUUID}/component/templates:
    get:
      tags:
      - 组件
      summary: 列出当前团队下的所有的组件模版
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      responses:
        "200":
          description: 返回组件模版列表
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/TemplatesResponse'
        "500":
          description: 服务端错误

  /team/{teamUUID}/project/{projectUUID}/components:
    get:
      tags:
      - 组件
      summary: 列出当前项目下的所有的组件
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      responses:
        "200":
          description: 返回项目下组件列表
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/ComponentsResponse'
        "500":
          description: 服务端错误
  /team/{teamUUID}/project/{projectUUID}/components/update:
    post:
      tags:
      - 组件
      summary: 批量更新所有的组件更新
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      requestBody:
        description: 请求的参数
        required: true
        content:
          application/json:
            schema:
              $ref: '/spec/api/project/component/schemas.yaml#/ComponentsRequest'
      responses:
        "200":
          description: 返回项目下组件列表
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/ComponentsResponse'
        "400":
          description: 错误的请求
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '/spec/api/project/component/errors.yaml#/MalformedJSON'
                  - $ref: '/spec/api/project/component/errors.yaml#/MissingParameterComponentTemplateUUID'
                  - $ref: '/spec/api/project/component/errors.yaml#/MissingParameterComponentUUID'

        "500":
          description: 服务端错误
