openapi: 3.0.0
servers:
  - description: localhost
    url: http://localhost:9001/
info:
  title: 组件视图
  description: 组件中的视图相关api接口
  version: v1
parameters:
  Ones-Auth-Token:
    name: Ones-Auth-Token
    in: header
    description: Ones auth token
    required: true
    schema:
      type: string
  Ones-User-ID:
    name: Ones-User-ID
    in: header
    description: Ones user id
    required: true
    schema:
      type: string
  comUUID:
    name: comUUID
    in: path
    description: 组件 uuid
    required: true
    minLength: 8
    maxLength: 8
    schema:
      type: string
  projectUUID:
    name: projectUUID
    in: path
    description: 项目UUID
    required: true
    minLength: 16
    maxLength: 16
    schema:
      type: string
  teamUUID:
    name: teamUUID
    in: path
    description: 团队UUID
    required: true
    minLength: 8
    maxLength: 8
    schema:
      type: string
  viewUUID:
    name: viewUUID
    in: path
    description: 视图UUID
    required: true
    minLength: 8
    maxLength: 8
    schema:
      type: string
paths:
  /team/{teamUUID}/project/{projectUUID}/component/{comUUID}/user_views:
    get:
      tags:
      - 视图
      summary: 当前用户的视图
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      - $ref: '#/parameters/comUUID'
      responses:
        "200":
          description: 成功返回当前用户的视图
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/ComponentUserViewsResponse'
  /team/{teamUUID}/project/{projectUUID}/component/{comUUID}/user_view/{viewUUID}/delete:
    post:
      tags:
      - 视图
      summary: 删除当前用户的视图
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      - $ref: '#/parameters/comUUID'
      - $ref: '#/parameters/viewUUID'
      responses:
        "200":
          description: 成功返回当前用户的视图
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/UpdateResponse'
        "401":
          description: 无权限
  /team/{teamUUID}/project/{projectUUID}/component/{comUUID}/user_view/{viewUUID}/update:
    post:
      tags:
      - 视图
      summary: 更新当前用户的视图
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      - $ref: '#/parameters/comUUID'
      - $ref: '#/parameters/viewUUID'
      requestBody:
        description: 新的视图数据
        required: true
        content:
          application/json:
            schema:
              $ref: '/spec/api/project/component/schemas.yaml#/ViewRequest'
      responses:
        "200":
          description: 成功返回当前用户的视图
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/UpdateResponse'
        "401":
          description: 无权限
  /team/{teamUUID}/project/{projectUUID}/component/{comUUID}/user_views/add:
    post:
      tags:
      - 视图
      summary: 当前用户添加视图
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      - $ref: '#/parameters/comUUID'
      requestBody:
        description: 创建用户视图
        required: true
        content:
          application/json:
            schema:
              $ref: '/spec/api/project/component/schemas.yaml#/ViewRequest'
      responses:
        "200":
          description: 成功返回当前用户的视图
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/ComponentUserViewResponse'
  /team/{teamUUID}/project/{projectUUID}/component/{comUUID}/user_views/config:
    get:
      tags:
      - 视图
      summary: 当前用户的视图列表配置
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      - $ref: '#/parameters/comUUID'
      responses:
        "200":
          description: 成功返回当前用户的视图列表配置
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/ComponentUserViewConfigResponse'
        "401":
          description: 无权限
  /team/{teamUUID}/project/{projectUUID}/component/{comUUID}/user_views/config/update:
    post:
      tags:
      - 视图
      summary: 更新用户的视图配置（排序、是否显示等）
      consumes:
      - application/json
      parameters:
      - $ref: '#/parameters/Ones-User-ID'
      - $ref: '#/parameters/Ones-Auth-Token'
      - $ref: '#/parameters/teamUUID'
      - $ref: '#/parameters/projectUUID'
      - $ref: '#/parameters/comUUID'
      requestBody:
        description: 新的视图配置
        required: true
        content:
          application/json:
            schema:
              $ref: '/spec/api/project/component/schemas.yaml#/ConfigRequest'
      responses:
        "200":
          description: 成功返回当前用户的视图列表配置
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/component/schemas.yaml#/UpdateResponse'
        "401":
          description: 无权限