openapi: 3.0.0
info:
  title: 创建任务类型
  description: >-
    该接口支持以下功能：
    1. 创建一个任务类型
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/login:
    post:
      tags:
        - IssueType
      description: 创建一个任务类型
      operationId: IssueTypeAdd
      responses:
        '200':
          description: 返回任务类型信息
          content:
            application/json:
              schema:
                description: 返回任务类型信息
                type: object
                properties:
                  user:
                    $ref: '/spec/api/project/auth/schemas.yaml#/user'
                  teams:
                    type: array
                    items:
                      $ref: '/spec/api/project/auth/schemas.yaml#/team'
                  org:
                    $ref: '/spec/api/project/auth/schemas.yaml#/org'
        '400':
          description: 返回400时出现的错误
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '/spec/api/project/auth/errors.yaml#/MalformedJSON'
                  - $ref: '/spec/api/project/auth/errors.yaml#/MissingParameterUserEmail'
        '401':
          description: 用户名或者密码不正确
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureNotInAnyTeam'
                  - $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureInvalidPassword'
        '404':
          description: 找不到组织
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/NotFoundOrganization'
        '630':
          description: 用户不存在
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml/#/NotFoundUser'
        '801':
          description: 无效参数
          content:
            application/json:
              schema:
                oneOf:
                - description: password 格式不正确
                  type: object
                  properties:
                    errcode:
                      type: string
                      enum:
                        - InvalidParameter.User.Password.InvalidFormat
                    code:
                      type: integer
                      format: int32
                      enum:
                        - 801
                    type:
                      type: string
                      enum:
                        - InvalidParameter
                    model:
                      type: string
                      enum:
                        - User
                    field:
                      type: string
                      enum:
                        - password
                    reason:
                      type: string
                      enum:
                        - InvalidFormat
                  required:
                    - errcode
                    - code
                    - type
                    - model
                    - field
                    - reason
                - $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterUserEmailInvalidFormat'
                - $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterUserPhoneInvalidFormat'
        '813':
          description: 登陆已过期
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureExpired'
        '814':
          description: 团队中找不到 status === 1 且 team_member_status === 1 的用户
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureNotInAnyTeam'
        default:
          content:
            application/json:
              schema:
                $ref: '/spec/common/errors.yaml#/UnknownError'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                issue_type:
                  type: object
                  properties:
                    name:
                      $ref: '/api_schema/api/project/auth/schemas.yaml#/name'
                    icon:
                      $ref: '/api_schema/api/project/auth/schemas.yaml#/name'
                copy_from:
                  $ref: $ref: '/api_schema/api/project/auth/schemas.yaml#/copy_from'
              required:
                - issue_type
                - name 
                - icon             
        description: 请求内容为任务类型信息
        required: true
