openapi: 3.0.0
servers:
- description: localhost
  url: http://localhost:9001/
info:
  title: 项目接口
  description: 添加项目接口
  version: v1
parameters:
  Ones-Auth-Token:
    name: Ones-Auth-Token
    in: header
    description: Ones auth token
    required: true
    schema:
      type: string
  Ones-User-ID:
    name: Ones-User-ID
    in: header
    description: Ones user id
    required: true
    schema:
      type: string
  teamUUID:
    name: teamUUID
    in: path
    description: 团队UUID
    required: true
    minLength: 8
    maxLength: 8
    schema:
      type: string

paths:
  /team/{teamUUID}/tasks/add2:
    post:
      tags:
        - Auth
      description: 用户登陆
      operationId: authLogin
      responses:
        '200':
          description: 返回用户信息
          content:
            application/json:
              schema:
                description: 返回用户信息
                type: object
                properties:
                  user:
                    $ref: './api_schema/api/project/auth/schemas.yaml#/user'
                  teams:
                    type: array
                    items:
                      $ref: './api_schema/api/project/auth/schemas.yaml#/team'
                  org:
                    $ref: './api_schema/api/project/auth/schemas.yaml#/org'
        '400':
          description: 返回400时出现的错误
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: './api_schema/api/project/auth/errors.yaml#/MalformedJSON'
                  - $ref: './api_schema/api/project/auth/errors.yaml#/MissingParameterUserEmail'
        '401':
          description: 用户名或者密码不正确
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureNotInAnyTeam'
                  - $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureInvalidPassword'
        '404':
          description: 找不到组织
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/NotFoundOrganization'
        '630':
          description: 用户不存在
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/NotFoundUser'
        '801':
          description: 无效参数
          content:
            application/json:
              schema:
                oneOf:
                - description: password 格式不正确
                  type: object
                  properties:
                    errcode:
                      type: string
                      enum:
                        - InvalidParameter.User.Password.InvalidFormat
                    code:
                      type: integer
                      format: int32
                      enum:
                        - 801
                    type:
                      type: string
                      enum:
                        - InvalidParameter
                    model:
                      type: string
                      enum:
                        - User
                    field:
                      type: string
                      enum:
                        - password
                    reason:
                      type: string
                      enum:
                        - InvalidFormat
                  required:
                    - errcode
                    - code
                    - type
                    - model
                    - field
                    - reason
                - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterUserEmailInvalidFormat'
                - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterUserPhoneInvalidFormat'
        '813':
          description: 登陆已过期
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureExpired'
        '814':
          description: 团队中找不到 status === 1 且 team_member_status === 1 的用户
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureNotInAnyTeam'
        default:
          content:
            application/json:
              schema:
                $ref: './api_schema/common/errors.yaml#/UnknownError'
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
                properties:
                  email:
                    $ref: './api_schema/api/project/auth/schemas.yaml#/email'
                  password:
                    $ref: './api_schema/api/project/auth/schemas.yaml#/password'
                required:
                  - email
                  - password              
              - type: object
                properties:
                  phone:
                    $ref: './api_schema/api/project/auth/schemas.yaml#/phone'
                  password:
                    $ref: './api_schema/api/project/auth/schemas.yaml#/password'
                required:
                  - phone
                  - password
        description: 请求内容为用户的信息
        required: true