openapi: 3.0.0
info:
  title: project 通过email直接创建账号（私有部署）
  description: >-
    该接口支持以下功能：
    12. 通过email直接创建账号（私有部署）
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/add_account_directly:
    post:
      tags:
        - Auth
      description: 通过email直接创建账号（私有部署）
      operationId: AddAccountDirectly
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/schemas.yaml#/email'
        '401':
          description: 登录凭证失效
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureInvalidToken'
        '403':
          description: 邀请成员无权限访问
          content:
            application/json:
              schema:
                type: object
                properties:
                  errcode:
                    type: string
                    enum:
                      - PermissionDenied.InviteMember
                  code:
                    type: integer
                    enum:
                      - 403
                  type:
                    type: string
                    enum:
                      - PermissionDenied
                  reason:
                    type: string
                    enum:
                      - InviteMember
                required:
                  - errcode
                  - code
                  - type
                  - reason
        '404':
          description: 找不到URL/找不到组织
          content:
            application/json:
              schema:
                oneOf:
                  - description: 找不到URL
                    type: object
                    properties:
                      errcode:
                        type: string
                        enum:
                          - NotFound.URL
                      code:
                        type: integer
                        format: int32
                        enum:
                          - 404
                      type:
                        type: string
                        enum:
                          - NotFound
                      field:
                        type: string
                        enum:
                          - URL
                    required:
                      - errcode
                      - code
                      - type
                      - model
                  - $ref: '/spec/api/project/auth/errors.yaml#/NotFoundOrganization'
        '621':
          description: 邮箱已存在
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AlreadyExistsUserEmailExists'
        '801':
          description: 邮箱格式不正确
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterUserEmailInvalidFormat'
        '802':
          description: 登录凭证为空
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureMissingToken'
        '807':
          description: 找不到团队
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/NotFoundTeam'
        '824':
          description: 成员超出限制
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/LimitExceededTeamMember'
        default:
          content:
            application/json:
              schema:
                $ref: '/spec/common/errors.yaml#/UnknownError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '/spec/api/project/auth/schemas.yaml#/user'
        description: 通过email直接创建账号（私有部署）