openapi: 3.0.0
info:
  title: project 验证邮箱是否可注册
  description: >-
    该接口支持以下功能：
    11. 验证邮箱是否可注册
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/check_email:
    post:
      tags:
        - Auth
      description: 验证邮箱是否可注册
      operationId: CheckEmail
      responses:
        '200':
          description: 验证成功
          content:
            application/json:
              schema:
                $ref: '/spec/common/schemas.yaml#/SuccessResponse'
        '621':
          description: 邮箱已存在
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AlreadyExistsUserEmailExists'
        '801':
          description: 邮箱格式不正确
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterUserEmailInvalidFormat'
        default:
          content:
            application/json:
              schema:
                $ref: '/spec/common/errors.yaml#/UnknownError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '/spec/api/project/auth/schemas.yaml#/email'
        description: 验证邮箱请求