openapi: 3.0.0
info:
  title: project 登陆
  description: >-
    该接口支持以下功能：
    7. 使用验证码创建一个新团队及团队负责人新账户
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/create_team:
    post:
      tags:
        - Auth
      description: 使用验证码创建一个新团队及团队负责人新账户
      operationId: CreateTeam
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/schemas.yaml#/LoginResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema: 
                oneOf:
                  - $ref: './api_schema/api/project/auth/errors.yaml#/MalformedJSON'
                  - $ref: './api_schema/api/project/auth/errors.yaml#/MissingParameterUserEmail'
        '401':
          description: 参数错误
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureNotInAnyTeam'
                  - $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureInvalidPassword'
        '404':
          description: 找不到组织
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/NotFoundOrganization'
        '605':
          description: 验证码不存在或者无效
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/VerificationFailureInvalidCode'
        '606':
          description: 验证码过期（有效期为15分钟）
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/VerificationFailureCodeExpired'
        '621':
          description: 邮箱已存在
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/AlreadyExistsUserEmailExists'
        '630':
          description: 用户不存在
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/NotFoundUser'
        '801':
          description: 参数有误
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterEmailInvalidFormat'
                  - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterPasswordInvalidFormat'
                  - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterPhoneInvalidFormat'
                  - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterUserNameTooLong'
                  - description: 团队名称超长或者团队名称为空
                    type: object
                    properties:
                      errcode:
                        type: string
                        enum:
                          - InvalidParameter.Team.Name.TooLong
                      code:
                        type: integer
                        format: int32
                        enum:
                          - 801
                      type:
                        type: string
                        enum:
                          - InvalidParameter
                      model:
                        type: string
                        enum:
                          - Team
                      field:
                        type: string
                        enum:
                          - Name
                      reason:
                        type: string
                        enum:
                          - TooLong
                    required:
                      - errcode
                      - code
                      - type
                      - model
                      - field
                      - reason
                  - $ref: './api_schema/api/project/auth/errors.yaml#/VerificationFailureInvalidCode'
        '813':
          description: 登陆已过期
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureExpired'
        '814':
          description: 团队中找不到 status === 1 且 team_member_status === 1 的用户
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureNotInAnyTeam'
        default:
          content:
            application/json:
              schema:
                $ref: './api_schema/common/errors.yaml#/UnknownError'
      requestBody:
        content:
          application/json:
            schema:
              description: 创建团队请求
              type: object
              properties:
                name:
                  description: 用户名称
                  type: string
                  maxLength: 16
                team_name:
                  description: 团队名称
                  type: string
                  maxLength: 16
                team_scale:
                  description: 团队规模
                  type: string
                industry:
                  description: 行业
                  type: string
                email:
                  $ref: './api_schema/api/project/auth/schemas.yaml#/email'
                phone:
                  $ref: './api_schema/api/project/auth/schemas.yaml#/phone'
                password:
                  $ref: './api_schema/api/project/auth/schemas.yaml#/password'
                need_support:
                  description: 是否需要支持
                  type: boolean
                phone_code:
                  description: 手机校验码
                  type: string
                referrer:
                  description: 渠道信息
                  type: string
                keyword:
                  description: 搜索关键词
                  type: string
                channel:
                  description: 渠道来源
                  type: string
              required:
                - name
                - team_name
                - email
                - phone
                - password
                - phone_code
        description: 使用验证码创建一个新团队及团队负责人新账户