openapi: 3.0.0
info:
  title: project 登陆
  description: >-
    该接口支持以下功能:
    1. 用户登陆 
    2. 请求发送重置密码验证码
    3. 重置密码
    4. 接受邀请加入团队
    5. 发送验证码，校验手机号是否有效或已被使用
    6. 检查手机验证码
    7. 创建团队
    8. 申请支持（联系我们）
    9. 验证邮箱验证码（激活邮箱）
    10. 根据token获取登陆信息
    11. 验证邮箱是否可注册
    12. 通过email直接创建账号（私有部署）
  version: v1
paths:
  /auth/login:
    $ref: '/spec/api/project/auth/login.yaml#/paths/~1auth~1login'
  /auth/request_reset_code:
    $ref: '/spec/api/project/auth/request_reset_code.yaml#/paths/~1auth~1request_reset_code'    
  /auth/reset_password:
    $ref: '/spec/api/project/auth/reset_password.yaml#/paths/~1auth~1reset_password'
  /auth/invite_join_team:
    $ref: '/spec/api/project/auth/invite_join_team.yaml#/paths/~1auth~1invite_join_team'
  /auth/verify_phone:
    $ref: '/spec/api/project/auth/verify_phone.yaml#/paths/~1auth~1verify_phone'
  /auth/check_phone_code:
    $ref: '/spec/api/project/auth/check_phone_code.yaml#/paths/~1auth~1check_phone_code'
  /auth/create_team:
    $ref: '/spec/api/project/auth/create_team.yaml#/paths/~1auth~1create_team'
  /auth/request_support:
    $ref: '/spec/api/project/auth/request_support.yaml#/paths/~1auth~1request_support'
  /auth/check_email_code:
    $ref: '/spec/api/project/auth/check_email_code.yaml#/paths/~1auth~1check_email_code'
  /auth/token_info:
    $ref: '/spec/api/project/auth/token_info.yaml#/paths/~1auth~1token_info'
  /auth/check_email:
    $ref: '/spec/api/project/auth/check_email.yaml#/paths/~1auth~1check_email'
  /auth/add_account_directly:
    $ref: '/spec/api/project/auth/add_account_directly.yaml#/paths/~1auth~1add_account_directly'
servers:
  - url: 'https://api.ones.ai/project/v1/'
