openapi: 3.0.0
info:
  title: project 
  description: >-
    该接口支持以下功能：
    8. 申请支持（联系我们）
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/request_support:
    get:
      tags:
        - Auth 
      description: 提交表单申请支持（联系我们）
      operationId: RequestSupport
      responses:
        '200':
          description: 提交表单成功
          content:
            application/json:
              schema:
                $ref: '/spec/common/schemas.yaml#/SuccessResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '/spec/api/project/auth/errors.yaml#/MalformedJSON'
                  - description: team uuid 为空
                    type: object
                    properties:
                      errcode:
                        type: string
                        enum:
                          - InvalidParameter.Team.UUID.Empty
                      code:
                        type: string
                        format: int32
                        enum:
                          - 400
                      type:
                        type: string
                        enum:
                          - InvalidParameter
                      model:
                        type: string
                        enum:
                          - Team
                      field:
                        type: string
                        enum:
                          - UUID
                      reason:
                        type: string
                        enum:
                          - Empty
                    required:
                      - errcode
                      - code
                      - type
                      - model
                      - field
                      - reason
        '401':
          description: 登陆凭证失效
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureInvalidToken'
        '600':
          description: email 格式不正确
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterUserEmailInvalidFormat'
        '622':
          description: '#手机格式不正确'
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterUserPhoneInvalidFormat'
        '802':
          description: 登录凭证为空
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureMissingToken'
        default:
          content:
            application/json:
              schema:
                $ref: '/spec/common/errors.yaml#/UnknownError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: 提交表单申请支持请求
              properties:
                name:
                  description: 用户名称
                  type: string
                  maxLength: 16
                team_name:
                  description: 团队名称
                  type: string
                  maxLength: 16
                team_scale:
                  description: 团队规模
                  type: string
                industry:
                  description: 行业
                  type: string
                email:
                  $ref: '/spec/api/project/auth/schemas.yaml#/email'
                phone:
                  $ref: '/spec/api/project/auth/schemas.yaml#/phone'
                jsonpcallback:
                  description: 如果这个值存在，则返回 jsonp，否则返回 json
                  type: string
                source:
                  description: '线上入口来源 (create_team:创建团队;upgrade:ONES Project;contact_us:官网)'
                  type: string
                  enum:
                    - create_team
                    - upgrade
                    - contact_us
              required:
                - name
                - team_name
                - email
                - phone