openapi: 3.0.0
info:
  title: project 重置密码验证码
  description: >-
    该接口支持以下功能：
    3.重置密码
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/reset_password:
    post:
      tags:
        - Auth
      description: 重置密码
      operationId: ResetPassword
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/schemas.yaml#/LoginResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '/spec/api/project/auth/errors.yaml#/MalformedJSON'
                  - $ref: '/spec/api/project/auth/errors.yaml#/MissingParameterEmail'
                  - $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterEmailInvalidFormat'
                  - $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterPhoneInvalidFormat'
                  - $ref: '/spec/api/project/auth/errors.yaml#/InvalidParameterPasswordInvalidFormat'
                  - $ref: '/spec/api/project/auth/errors.yaml#/VerificationFailureInvalidCode'
        '616':
          description: 未找到匹配的验证码
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/VerificationFailureInvalidCode'
        '617':
          description: 验证码已过期
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/VerificationFailureCodeExpired'
        '620':
          description: 用户不存在
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/NotFoundUser'
        default:
          content:
            application/json:
              schema:
                $ref: '/spec/common/errors.yaml#/UnknownError'
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    email:
                      type: string
                    password:
                      $ref: '/spec/api/project/auth/schemas.yaml#/password'
                    code:
                      description: 验证码
                      type: string
                      maxLength: 6
                  required:
                    - email
                    - password
                    - code
                - type: object
                  properties:
                    phone:
                      $ref: '/spec/api/project/auth/schemas.yaml#/phone'
                    password:
                      $ref: '/spec/api/project/auth/schemas.yaml#/password'
                    code:
                      description: 验证码
                      type: string
                      maxLength: 6
                  required:
                    - phone
                    - password
                    - code
        description: 重置密码
        required: true
