openapi: 3.0.0
info:
  title: project 根据token获取登录信息
  description: >-
    该接口支持以下功能：
    10. 根据token获取登录信息
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/token_info:
    get:
      tags:
        - Auth
      description: 根据token获取登录信息
      operationId: TokenInfo
      parameters:
        - $ref: '/spec/common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: '/spec/common/parameters.yaml#/parameters/Ones-Auth-Token'
      responses:
        '200':
          description: 获取tokeninfo成功
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/schemas.yaml#/LoginResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/MalformedJSON'
        '401':
          description: 登录凭证失效
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureInvalidToken'
        '404':
          description: 找不到组织
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/NotFoundOrganization'
        '615':
          description: 找不到用户
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/NotFoundUser'
        '802':
          description: 登录凭证为空
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureMissingToken'
        '807':
          description: 找不到团队
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/NotFoundTeam'
        '813':
          description: 登陆已过期
          content:
            application/json:
              schema:
                $ref: '/spec/api/project/auth/errors.yaml#/AuthFailureExpired'
        default:
          content:
            application/json:
              schema:
                $ref: '/spec/common/errors.yaml#/UnknownError'