openapi: 3.0.0
info:
  title: project 接受邀请加入团队
  description: >-
    该接口支持以下功能：
    4. 接受邀请加入团队
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /auth/invite_join_team:
    post:
      tags:
        - Auth
      description: 接受邀请加入团队
      operationId: InviteJoinTeam
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/schemas.yaml#/LoginResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/MalformedJSON'
        '401':
          description: 已有用户被邀请加入时新密码和旧密码不同
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/AuthFailureInvalidPassword'
        '404':
          description: 找不到组织
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/NotFoundOrganization'
        '410':
          description: 已加入另一个组织
          content:
            application/json:
              schema:
                ConstraintViolationJoinOtherOrganization:
                  description: 已加入另一个组织
                  type: object
                  properties:
                    errcode:
                      type: string
                      enum:
                        - ConstraintViolation.JoinOtherOrganization
                    code:
                      type: integer
                      format: int32
                      enum:
                        - 401
                    type:
                      type: string
                      enum:
                        - ConstraintViolation
                    reason:
                      type: string
                      enum:
                        - JoinOtherOrganization
                  required:
                    - errcode
                    - code
                    - type
                    - reason
        '612':
          description: 邀请码错误
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/VerificationFailureInvalidCode'
        '613':
          description: 邀请码过期
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/VerificationFailureCodeExpired'
        '624':
          description: 没找到邀请码
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/VerificationFailureInvalidCode'
        '630':
          description: 用户不存在
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/NotFoundUser'
        '801':
          description: 参数错误
          content:
            application/json:
              schema:
                oneOf:
                - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterEmailInvalidFormat'
                - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterPasswordInvalidFormat'
                - description: 邀请码格式错误
                  type: object
                  properties:
                    errcode:
                      type: string
                      enum:
                        - InvalidParameter.InviteCode.InvalidFormat
                    code:
                      type: integer
                      format: int32
                      enum:
                        - 801
                    type:
                      type: string
                      enum:
                        - InvalidParameter
                    field:
                      type: string
                      enum:
                        - InviteCode
                    reason:
                      type: string
                      enum:
                        - InvalidFormat
                  required:
                    - errcode
                    - code
                    - type
                    - field
                    - reason
                - $ref: './api_schema/api/project/auth/errors.yaml#/InvalidParameterUserNameTooLong'
        '807':
          description: 团队不存在
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/NotFoundTeam'
        '824':
          description: 成员数超出限制
          content:
            application/json:
              schema:
                $ref: './api_schema/api/project/auth/errors.yaml#/LimitExceededTeamMember'
        default:
          content:
            application/json:
              schema:
                $ref: './api_schema/common/errors.yaml#/UnknownError'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: './api_schema/api/project/auth/schemas.yaml#/email'
                phone:
                  $ref: './api_schema/api/project/auth/schemas.yaml#/phone'
                password:
                  $ref: './api_schema/api/project/auth/schemas.yaml#/password'
                name:
                  description: 用户名称
                  type: string
                  minLength: 0
                  maxLength: 16
                invite_code:
                  description: 邀请码
                  type: string
                  minLength: 0
                  maxLength: 32
              required:
                - email
                - password
                - name
                - invite_code
        description: 接受邀请加入团队
        required: true  