openapi: 3.0.0
info:
  title: project 项目
  description: >-
    该接口支持以下功能：
    2.修改项目
  version: v1
servers:
  - url: 'https://api.ones.ai/project/v1/'
paths:
  /team/{teamUUID}/projects/update:
    post:
      tags:
        - Project
      description: 修改项目
      operationId: ProjectsUpdate
      parameters:
        - $ref: './api_schema/common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: './api_schema/common/parameters.yaml#/parameters/Ones-Auth-Token'
        - $ref: './api_schema/common/parameters.yaml#/parameters/teamUUID'
      requestBody:
        description: 修改项目信息
        content:
          application/json:
            schema:
              type: object
              properties:
                projects:
                  type: array
                  items:
                    $ref: '#/components/schemas/ProjectInfo'
              required:
                - projects
      responses:
        '200':
          description: 修改成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    items:
                      $ref: './api_schema/api/project/project/schemas.yaml#ProjectInfo' 
                  bad_projects:
                    type: array
                    items:
                      anyOf:
                        - $ref: './api_schema/api/project/project/errors.yaml#/PermissionDeniedManageProject'
                        - $ref: './api_schema/api/project/project/errors.yaml#/InvalidParameterProjectNameTooLongWithUUID'
                        - $ref: './api_schema/api/project/project/errors.yaml#/InvalidParameterProjectAnnouncementTooLongWithUUID'
                        - $ref: './api_schema/api/project/project/errors.yaml#/InvalidParameterProjectDeadlineInvalidFormatWithUUID'
                        - $ref: './api_schema/api/project/project/errors.yaml#/InvalidParameterProjectStatusInvalidTypeWithUUID'
                  server_update_stamp:
                    $ref: './api_schema/api/project/project/schemas.yaml#/server_update_stamp'
        '403':
          description: 无操作权限
          content:
            application/json:
              schema:
                  $ref: './api_schema/api/project/project/errors.yaml#/AccessDeniedTeam'
        default:
          content:
            application/json:
              schema:
                $ref: './api_schema/common/errors.yaml#/UnknownError'
components:
  schemas:
    ProjectInfo:
      description: 添加项目信息
      type: object
      properties:
        uuid:
          description: 项目uuid
          type: string
          maxLength: 16
        name:
          description: 项目名称
          type: string
          minLength: 0
          maxLength: 128
        status:
          description: >-
            项目状态
            1.进行中
            2.已删除
            3.归档
          type: integer
          format: int32
          enum:
            - 1
            - 2
            - 3
        announcement:
          description: 项目公告
          type: string
          minLength: 0
          maxLength: 512
        deadline:
          description: 截止时间，与1970的秒差
          type: integer
          format: int64
        is_pin:
          description: 是否置顶
          type: boolean
        is_open_email_notify:
          description: 是否开通邮件通知
          type: boolean
        admins:
          description: 项目管理员（user_uuid数组）
          type: array
          items:
            type: string
        task_update_time:
          description: 项目下任务更新时间（单位秒）
          type: integer
          format: int64
      required:
        - uuid


